"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DB_PASSWORD = exports.DB_USER = exports.DB_URI = exports.API_PORT = exports.CLIENT_URL = exports.API_URL = exports.SECRET_KEY = void 0;
const dotenv_1 = require("dotenv");
(0, dotenv_1.config)();
exports.SECRET_KEY = process.env.SECRET_KEY || '$2b$10$ka87I5mFLWjggfCEVj1uc.4u5xkzFepZ5.V68UL5kahwKzaFTAIdW';
exports.API_URL = process.env.API_URL || 'http://localhost:5173';
exports.CLIENT_URL = process.env.CLIENT_URL || 'http://localhost:3000';
exports.API_PORT = process.env.API_PORT || '3000';
exports.DB_URI = process.env.DB_URI || 'mongodb://localhost:27017/inventory_db';
exports.DB_USER = process.env.DB_USER || 'root';
exports.DB_PASSWORD = process.env.DB_PASSWORD || 'root';
