"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const globalConstants_1 = require("./config/globalConstants");
const index_routes_1 = __importDefault(require("./routes/index.routes"));
const morgan_1 = __importDefault(require("morgan"));
const passport_1 = __importDefault(require("passport"));
const passport_2 = __importDefault(require("./middlewares/passport"));
const cors_1 = __importDefault(require("cors"));
require("./db");
const app = (0, express_1.default)();
app.use((0, morgan_1.default)('dev'));
app.use(express_1.default.json());
app.use((0, cors_1.default)({ origin: globalConstants_1.CLIENT_URL }));
passport_1.default.use(passport_2.default);
app.use('/api/', index_routes_1.default);
app.listen(globalConstants_1.API_PORT, () => console.log(globalConstants_1.API_URL));
